name: nightly-benchmark
on:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch: {}
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate dummy data
        run: python data_samples/generate_dummy_las.py --out data_samples/site01.las --epsg 6677
      - name: Run extraction
        run: python scripts/extract_and_vectorize.py --in data_samples/site01.las --epsg 6677 --roi 40 --bev 0.03 --mode auto --out out/site01.dxf
      - name: Run benchmark
        run: python scripts/eval_benchmark.py --bench eval/bench_list.csv --report out/report.html
      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: nightly-report
          path: out/report.html
