features:
  include:
    - length_m
    - width_m
    - curvature
    - stripe_count
    - parallelism
    - angle_deg
    - intensity_mean
  normalize: true
lgbm:
  model_path: models/lgbm_default.txt
  max_depth: 6
  n_estimators: 150
  learning_rate: 0.1
  class_weights:
    road_line: 1.0
    stop_line: 1.2
    crosswalk: 1.5
    curb: 1.1
thresholds:
  default: 0.55
  ui_min: 0.3
  ui_max: 0.9
random_state: 42
