lines:
  ppht:
    rho: 1
    theta_deg: 1
    threshold: 80
    min_line_length: 5
    max_line_gap: 3
  nms:
    distance_m: 0.1
    angle_deg: 7
    overlap_ratio: 0.6
  reconnect:
    max_gap_m: 0.5
    angle_tol_deg: 8
  curvature:
    arc_min_length_m: 1.0
crosswalk:
  min_stripes: 3
  stripe_spacing_m: 0.4
  stripe_width_m: 0.3
  orientation_tolerance_deg: 10
curb:
  height_step_min_m: 0.12
  normal_angle_change_deg: 25
  connect_gap_m: 0.6
fallback_image_route:
  otsu_blur: 3
  morphology_kernel: 3
  hough_threshold: 60
