version: "3.8"
services:
  rmc:
    build: .
    volumes:
      - .:/app
    command: python scripts/extract_and_vectorize.py --help
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
